import 'controllers/noodle.dart';

List<Noodle> kFactoryNoodles = [
  Noodle(
    id: 1,
    name: "Ramen Lord's Tokyo Style Noodle",
    hydration: 38,
    kansui: 1.2000000000000002,
    salt: 1,
    sodium: 40,
    weight: 100,
    portions: 2,
    flourAPercentage: 99,
    flourBPercentage: 1,
    flourCPercentage: 0,
    flourAIndex: 63,
    flourBIndex: 111,
    flourCIndex: 2,
    proteinPercentage: 14.018793273986155,
    flourFlagPosition: 5,
    flourSelectedPosition: 1,
    adjunctNumber: 2,
    adjunctIndexes: [6, 7, 0, 0, 0],
    adjunctPercentages: [1, 0.1, 1, 1, 1],
    cutSizeIndex: 5,
  ),
  Noodle(
    id: 2,
    name: "Ramen Lord's New Wave Tokyo Style Noodle",
    hydration: 38,
    kansui: 1.2000000000000002,
    salt: 1,
    sodium: 40,
    weight: 100,
    portions: 2,
    flourAPercentage: 90,
    flourBPercentage: 10,
    flourCPercentage: 0,
    flourAIndex: 63,
    flourBIndex: 109,
    flourCIndex: 2,
    proteinPercentage: 12.739861523244313,
    flourFlagPosition: 5,
    flourSelectedPosition: 1,
    adjunctNumber: 2,
    adjunctIndexes: [6, 7, 0, 0, 0],
    adjunctPercentages: [1, 0.1, 1, 1, 1],
    cutSizeIndex: 5,
  ),
  Noodle(
    id: 3,
    name: "Ramen Lord's Jiro Noodle",
    hydration: 36,
    kansui: 1,
    salt: 1,
    sodium: 40,
    weight: 100,
    portions: 2,
    flourAPercentage: 100,
    flourBPercentage: 0,
    flourCPercentage: 0,
    flourAIndex: 27,
    flourBIndex: 1,
    flourCIndex: 2,
    proteinPercentage: 14.199999999999998,
    flourFlagPosition: 5,
    flourSelectedPosition: 0,
    adjunctNumber: 0,
    cutSizeIndex: 5,
  ),
  Noodle(
    id: 4,
    name: "Ramen Lord's Sapporo Style Noodle",
    hydration: 38,
    kansui: 1.6000000000000005,
    salt: 1,
    sodium: 80,
    weight: 100,
    portions: 2,
    flourAPercentage: 99,
    flourBPercentage: 1,
    flourCPercentage: 0,
    flourAIndex: 63,
    flourBIndex: 111,
    flourCIndex: 2,
    proteinPercentage: 13.61630218687873,
    flourFlagPosition: 5,
    flourSelectedPosition: 1,
    adjunctNumber: 2,
    adjunctIndexes: [8, 7, 0, 0, 0],
    adjunctPercentages: [0.5, 0.1, 1, 1, 1],
    cutSizeIndex: 5,
  ),
  Noodle(
    id: 5,
    name: "Ramen Lord's Makeshift-Hakata Style Noodle",
    hydration: 35,
    kansui: 0.5000000000000001,
    salt: 1,
    sodium: 20,
    weight: 100,
    portions: 2,
    flourAPercentage: 99,
    flourBPercentage: 1,
    flourCPercentage: 0,
    flourAIndex: 105,
    flourBIndex: 111,
    flourCIndex: 2,
    proteinPercentage: 13.62,
    flourFlagPosition: 5,
    flourSelectedPosition: 1,
    adjunctNumber: 0,
  ),
  Noodle(
    id: 6,
    name: "Ramen Lord's Kitakata Style Noodle",
    hydration: 45,
    kansui: 1.9000000000000008,
    salt: 1.0,
    sodium: 100,
    weight: 100,
    portions: 2,
    flourAPercentage: 95,
    flourBPercentage: 5,
    flourCPercentage: 0,
    flourAIndex: 62,
    flourBIndex: 110,
    flourCIndex: 2,
    proteinPercentage: 11.215,
    flourFlagPosition: 5,
    flourSelectedPosition: 1,
    cutSizeIndex: 10,
    cutShapeIndex: 1,
  ),
  Noodle(
    id: 7,
    name: "Ramen Lord's Akayu Style Noodle",
    hydration: 42,
    kansui: 1.2000000000000002,
    salt: 1.0,
    sodium: 42,
    weight: 100,
    portions: 2,
    flourAPercentage: 100,
    flourBPercentage: 0,
    flourCPercentage: 0,
    flourAIndex: 63,
    flourBIndex: 110,
    flourCIndex: 2,
    proteinPercentage: 12.7,
    flourFlagPosition: 5,
    flourSelectedPosition: 0,
    cutSizeIndex: 10,
    cutShapeIndex: 1,
  ),
  Noodle(
    id: 8,
    name: "Ramen Lord's Thick Tsukemen Noodle",
    hydration: 40,
    kansui: 1.0,
    salt: 1.0,
    sodium: 40,
    weight: 100,
    portions: 2,
    flourAPercentage: 94,
    flourBPercentage: 6,
    flourCPercentage: 0,
    flourAIndex: 106,
    flourBIndex: 72,
    flourCIndex: 2,
    proteinPercentage: 10.24,
    flourFlagPosition: 5,
    flourSelectedPosition: 1,
    cutSizeIndex: 10,
    cutShapeIndex: 1,
  ),
  Noodle(
    id: 9,
    name: "Ramen Lord's New Tsukemen Noodle",
    hydration: 40,
    kansui: 1.0,
    salt: 1.0,
    sodium: 40,
    weight: 100,
    portions: 2,
    flourAPercentage: 70,
    flourBPercentage: 30,
    flourCPercentage: 0,
    flourAIndex: 67,
    flourBIndex: 68,
    flourCIndex: 2,
    proteinPercentage: 12.57,
    flourFlagPosition: 5,
    flourSelectedPosition: 1,
    cutSizeIndex: 7,
    cutShapeIndex: 1,
  ),
  Noodle(
    id: 10,
    name: "Ramen Lord's Taishoken Style Tsukemen Noodle",
    hydration: 37,
    kansui: 1,
    salt: 1,
    sodium: 100,
    weight: 100,
    portions: 2,
    flourAPercentage: 60,
    flourBPercentage: 40,
    flourCPercentage: 0,
    flourAIndex: 62,
    flourBIndex: 68,
    flourCIndex: 2,
    proteinPercentage: 10.71153846153846,
    flourFlagPosition: 5,
    flourSelectedPosition: 1,
    adjunctNumber: 1,
    adjunctIndexes: [10, 0, 0, 0, 0],
    adjunctPercentages: [4, 1, 1, 1, 1],
    cutSizeIndex: 7,
    cutShapeIndex: 1,
  ),
  Noodle(
    id: 11,
    name: "Ramen Lord's Tapioca Tsukemen Noodle",
    hydration: 40,
    kansui: 1,
    salt: 1,
    sodium: 40,
    weight: 100,
    portions: 2,
    flourAPercentage: 90,
    flourBPercentage: 10,
    flourCPercentage: 0,
    flourAIndex: 106,
    flourBIndex: 110,
    flourCIndex: 2,
    proteinPercentage: 9.2,
    flourFlagPosition: 5,
    flourSelectedPosition: 1,
    adjunctNumber: 0,
    cutSizeIndex: 7,
    cutShapeIndex: 1,
  ),
  Noodle(
    id: 12,
    name: "Ramen Lord's Mazesoba Noodle",
    hydration: 36,
    kansui: 1,
    salt: 1,
    sodium: 80,
    weight: 100,
    portions: 2,
    flourAPercentage: 100,
    flourBPercentage: 0,
    flourCPercentage: 0,
    flourAIndex: 106,
    flourBIndex: 1,
    flourCIndex: 2,
    proteinPercentage: 12.172647914645973,
    flourFlagPosition: 5,
    flourSelectedPosition: 0,
    adjunctNumber: 2,
    adjunctIndexes: [6, 7, 0, 0, 0],
    adjunctPercentages: [3, 0.1, 1, 1, 1],
    cutSizeIndex: 7,
    cutShapeIndex: 1,
  ),
];
