import 'package:flutter/foundation.dart';

const List<Map> kFlourListGeneric = [
  <String, dynamic>{"name": "* Generic bread flour", "protein": 13.0},
  <String, dynamic>{"name": "* Generic AP flour", "protein": 10.0},
  <String, dynamic>{"name": "* Generic cake flour", "protein": 7.00},
  <String, dynamic>{"name": "* Generic rye flour", "protein": 11.0},
  <String, dynamic>{"name": "* Generic rice flour", "protein": 6.0},
  <String, dynamic>{"name": "* Generic tapioca flour", "protein": 2.0},
  <String, dynamic>{"name": "* Vital wheat gluten (75% protein)", "protein": 75.0},
  <String, dynamic>{"name": "* Vital wheat gluten (80% protein)", "protein": 80.0},
];

const List<Map> kFlourListItaly = [
  <String, dynamic>{"name": "🇮🇹 Caputo 00 Americana Flour", "protein": 14.25},
  <String, dynamic>{"name": "🇮🇹 Caputo 00 Chef's Flour", "protein": 13.00},
  <String, dynamic>{"name": "🇮🇹 Caputo 00 Extra Flour", "protein": 11.00},
  <String, dynamic>{"name": "🇮🇹 Caputo 00 Rinforzato Flour", "protein": 12.50},
  <String, dynamic>{"name": "🇮🇹 Caputo A Metro Flour", "protein": 13.25},
  <String, dynamic>{"name": "🇮🇹 Caputo Biologica Flour", "protein": 12.00},
  <String, dynamic>{"name": "🇮🇹 Caputo Classica Flour", "protein": 11.50},
  <String, dynamic>{"name": "🇮🇹 Caputo Nuvola  Flour", "protein": 12.50},
  <String, dynamic>{"name": "🇮🇹 Caputo Nuvola Super Flour", "protein": 13.50},
  <String, dynamic>{"name": "🇮🇹 Caputo Oro Flour", "protein": 14.50},
  <String, dynamic>{"name": "🇮🇹 Caputo Pizzaria Flour", "protein": 12.50},
  <String, dynamic>{"name": "🇮🇹 Caputo Ricca Flour", "protein": 13.00},
  <String, dynamic>{"name": "🇮🇹 Caputo Saccorosso Flour", "protein": 13.00},
  <String, dynamic>{"name": "🇮🇹 Caputo Speciale Flour", "protein": 11.00},
  <String, dynamic>{"name": "🇮🇹 Caputo Superiore Flour", "protein": 11.50},
  <String, dynamic>{"name": "🇮🇹 Caputo Tipo 1 Flour", "protein": 13.00},
];

const List<Map> kFlourListJapan = [
  <String, dynamic>{"name": "🇯🇵 Nisshin Baguette Flour: Lis d'or Aube", "protein": 10.9},
  <String, dynamic>{"name": "🇯🇵 Nisshin Baguette Flour: Lys d'or", "protein": 10.7},
  <String, dynamic>{"name": "🇯🇵 Nisshin Baguette Flour: Solel d'or", "protein": 12.0},
  <String, dynamic>{"name": "🇯🇵 Nisshin Baguette Flour: Terroir Pur", "protein": 9.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: Aosemi", "protein": 12.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: Billion", "protein": 12.8},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: Blizzard Innova", "protein": 12.2},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: Camellia", "protein": 11.8},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: Duelio", "protein": 12.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: Echord", "protein": 11.9},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: Jazz", "protein": 12.3},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: King", "protein": 14.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: Legendaire", "protein": 12.2},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: Maison Kayser Trad.", "protein": 11.6},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: Million", "protein": 12.2},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: Number One", "protein": 11.2},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: Ocean", "protein": 13.0},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: Savory", "protein": 12.7},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: Super Camellia", "protein": 11.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Bread Flour: Super King", "protein": 13.8},
  <String, dynamic>{"name": "🇯🇵 Nisshin Buckwheat Blending Flour: Aosemi", "protein": 12.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Buckwheat Blending Flour: Camellia", "protein": 11.8},
  <String, dynamic>{"name": "🇯🇵 Nisshin Buckwheat Blending Flour: Furusato", "protein": 13.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Buckwheat Blending Flour: Million", "protein": 12.2},
  <String, dynamic>{"name": "🇯🇵 Nisshin Buckwheat Blending Flour: Miyabi", "protein": 13.2},
  <String, dynamic>{"name": "🇯🇵 Nisshin Buckwheat Blending Flour: Ocean", "protein": 13.0},
  <String, dynamic>{"name": "🇯🇵 Nisshin Noodle Flour: Aramusya", "protein": 12.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Noodle Flour: Kabukimono", "protein": 10.6},
  <String, dynamic>{"name": "🇯🇵 Nisshin Noodle Flour: Koshinotsubaki", "protein": 11.3},
  <String, dynamic>{"name": "🇯🇵 Nisshin Noodle Flour: Menhassyu", "protein": 9.4},
  <String, dynamic>{"name": "🇯🇵 Nisshin Noodle Flour: Menmuso", "protein": 12.0},
  <String, dynamic>{"name": "🇯🇵 Nisshin Noodle Flour: Menyuuki", "protein": 12.3},
  <String, dynamic>{"name": "🇯🇵 Nisshin Noodle Flour: Monro", "protein": 12.3},
  <String, dynamic>{"name": "🇯🇵 Nisshin Noodle Flour: Ocean", "protein": 13.0},
  <String, dynamic>{"name": "🇯🇵 Nisshin Noodle Flour: Ohanabatake", "protein": 10.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Noodle Flour: Reika", "protein": 10.3},
  <String, dynamic>{"name": "🇯🇵 Nisshin Noodle Flour: shikizan", "protein": 11.4},
  <String, dynamic>{"name": "🇯🇵 Nisshin Noodle Flour: Tohryumon", "protein": 10.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Noodle Flour: Toku-Hiryu", "protein": 10.8},
  <String, dynamic>{"name": "🇯🇵 Nisshin Noodle Flour: Toku-Number One", "protein": 11.2},
  <String, dynamic>{"name": "🇯🇵 Nisshin Noodle Flour: Waka", "protein": 12.0},
  <String, dynamic>{"name": "🇯🇵 Nisshin Pastry Flour: Angelight", "protein": 7.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Pastry Flour: Asahi", "protein": 8.1},
  <String, dynamic>{"name": "🇯🇵 Nisshin Pastry Flour: Ecriture", "protein": 9.2},
  <String, dynamic>{"name": "🇯🇵 Nisshin Pastry Flour: Flower", "protein": 8.3},
  <String, dynamic>{"name": "🇯🇵 Nisshin Pastry Flour: Marguerite", "protein": 8.6},
  <String, dynamic>{"name": "🇯🇵 Nisshin Pastry Flour: Mimosa", "protein": 9.6},
  <String, dynamic>{"name": "🇯🇵 Nisshin Pastry Flour: Omu", "protein": 10.0},
  <String, dynamic>{"name": "🇯🇵 Nisshin Pastry Flour: Super Violet", "protein": 6.2},
  <String, dynamic>{"name": "🇯🇵 Nisshin Pastry Flour: Toku-Omu", "protein": 9.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Pastry Flour: Violet", "protein": 7.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Pastry Flour: Yuki", "protein": 10.6},
  <String, dynamic>{"name": "🇯🇵 Nisshin Pizza Flour: Farina Da Salone", "protein": 11.7},
  <String, dynamic>{"name": "🇯🇵 Nisshin Pizza Flour: Rustica", "protein": 10.9},
  <String, dynamic>{"name": "🇯🇵 Nisshin Rye Flour: Alles Fein", "protein": 8.4},
  <String, dynamic>{"name": "🇯🇵 Nisshin Rye Flour: Alles Mittel", "protein": 8.4},
  <String, dynamic>{"name": "🇯🇵 Nisshin Rye Flour: Mehl Dunkel", "protein": 7.3},
  <String, dynamic>{"name": "🇯🇵 Nisshin Stone Ground Flour: Lawrence", "protein": 16.0},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Dosanko U", "protein": 10.0},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Hohun", "protein": 10.4},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Honsyu Hokusio", "protein": 10.0},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Kinsuzuran", "protein": 9.1},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Kintoun", "protein": 8.0},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Kumpu", "protein": 10.0},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Men no Hinauta", "protein": 11.7},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Men-Ishin", "protein": 7.2},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Menhassyu", "protein": 9.4},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Menmatsuri", "protein": 7.8},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Mugibatake", "protein": 8.4},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Sazanka", "protein": 9.0},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Shiki", "protein": 8.7},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Shin Menkyokaiden", "protein": 8.6},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Shiritsubaki", "protein": 8.8},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Toku-Suzume", "protein": 9.7},
  <String, dynamic>{"name": "🇯🇵 Nisshin Udon Flour: Warabe", "protein": 9.6},
  <String, dynamic>{"name": "🇯🇵 Nisshin Whole Wheat Flour: D", "protein": 10.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Whole Wheat Flour: Graham", "protein": 13.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Whole Wheat Flour: Graham Bread", "protein": 13.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Whole Wheat Flour: Super Fine Hard", "protein": 13.5},
  <String, dynamic>{"name": "🇯🇵 Nisshin Whole Wheat Flour: Super Fine Soft", "protein": 10.5},
];

const List<Map> kFlourListGermany = [
  <String, dynamic>{"name": "🇩🇪 Type 405 flour 8%", "protein": 8.0},
  <String, dynamic>{"name": "🇩🇪 Type 405 flour 8.5%", "protein": 8.5},
  <String, dynamic>{"name": "🇩🇪 Type 405 flour 9%", "protein": 9.0},
  <String, dynamic>{"name": "🇩🇪 Type 405 flour 9.5%", "protein": 9.5},
  <String, dynamic>{"name": "🇩🇪 Type 405 flour 10%", "protein": 10.0},
  <String, dynamic>{"name": "🇩🇪 Type 405 flour 10.5%", "protein": 10.5},
  <String, dynamic>{"name": "🇩🇪 Type 405 flour 11%", "protein": 11.0},
  <String, dynamic>{"name": "🇩🇪 Type 405 flour 11.5%", "protein": 11.5},
  <String, dynamic>{"name": "🇩🇪 Type 405 flour 12%", "protein": 12.0},
  <String, dynamic>{"name": "🇩🇪 Type 405 flour 12.5%", "protein": 12.5},
  <String, dynamic>{"name": "🇩🇪 Type 405 flour 13%", "protein": 13.0},
  <String, dynamic>{"name": "🇩🇪 Type 405 flour 13.5%", "protein": 13.5},
  <String, dynamic>{"name": "🇩🇪 Type 405 flour 14%", "protein": 14.0},
];

const List<Map> kFlourListSpain = [
  <String, dynamic>{"name": "🇪🇸 Gallo Harina de fuerza de trigo", "protein": 11.7},
  <String, dynamic>{"name": "🇪🇸 Gallo Harina de grano entero de trigo", "protein": 13.0},
  <String, dynamic>{"name": "🇪🇸 Gallo Harina de trigo", "protein": 9.0},
  <String, dynamic>{"name": "🇪🇸 Gallo Harina de trigo, especial repostería", "protein": 10.0},
  <String, dynamic>{"name": "🇪🇸 Gallo Harina de trigo, espelta integral", "protein": 14.0},
  <String, dynamic>{"name": "🇪🇸 Gallo Harina multicereales integral", "protein": 12.5},
  <String, dynamic>{"name": "🇪🇸 Hacendado Harina de fuerza", "protein": 12.2},
  <String, dynamic>{"name": "🇪🇸 Hacendado Harina de trigo", "protein": 10.0},
  <String, dynamic>{"name": "🇪🇸 Harimsa Especial Fuerza", "protein": 12.9},
];

const List<Map> kFlourListAustria = [
  <String, dynamic>{"name": "🇦🇹 Type W480 flour 8%", "protein": 8.0},
  <String, dynamic>{"name": "🇦🇹 Type W480 flour 8.5%", "protein": 8.5},
  <String, dynamic>{"name": "🇦🇹 Type W480 flour 9%", "protein": 9.0},
  <String, dynamic>{"name": "🇦🇹 Type W480 flour 9.5%", "protein": 9.5},
  <String, dynamic>{"name": "🇦🇹 Type W480 flour 10%", "protein": 10.0},
  <String, dynamic>{"name": "🇦🇹 Type W700 flour 9%", "protein": 9.0},
  <String, dynamic>{"name": "🇦🇹 Type W700 flour 9.5%", "protein": 9.5},
  <String, dynamic>{"name": "🇦🇹 Type W700 flour 10%", "protein": 10.0},
  <String, dynamic>{"name": "🇦🇹 Type W700 flour 10.5%", "protein": 10.5},
  <String, dynamic>{"name": "🇦🇹 Type W700 flour 11%", "protein": 11.0},
  <String, dynamic>{"name": "🇦🇹 Type W1600 flour 13%", "protein": 13.0},
  <String, dynamic>{"name": "🇦🇹 Type W1600 flour 13.5%", "protein": 13.5},
  <String, dynamic>{"name": "🇦🇹 Type W1600 flour 14%", "protein": 14.0},
  <String, dynamic>{"name": "🇦🇹 Type W1600 flour 14.5%", "protein": 14.5},
];

const List<Map> kFlourListUS = [
  <String, dynamic>{"name": "🇺🇸 Bob's Red Mill Artisan Bread Flour", "protein": 13.90},
  <String, dynamic>{"name": "🇺🇸 Bob's Red Mill Organic Stone Ground Whole Wheat", "protein": 14.00},
  <String, dynamic>{"name": "🇺🇸 Bob's Red Mill Organic Unbleached White AP", "protein": 11.00},
  <String, dynamic>{"name": "🇺🇸 Bob's Red Mill Unbleached White AP Flour", "protein": 11.00},
  <String, dynamic>{"name": "🇺🇸 Central Milling Artisan Bakers Craft ", "protein": 11.50},
  <String, dynamic>{"name": "🇺🇸 Central Milling Artisan Bakers Craft Plus", "protein": 11.50},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic 00 Normal", "protein": 11.20},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic Beehive", "protein": 10.25},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic Hard White Whole Wheat", "protein": 15.00},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic High Mountain", "protein": 13.50},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic Type 00 Reinforced", "protein": 13.80},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic Type 110", "protein": 12.50},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic Type 70 Malted", "protein": 11.50},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic Type 70 Pastry", "protein": 10.00},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic Type 85 Malted", "protein": 12.50},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic Type 85 Wheat Flour", "protein": 12.50},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic Unbleached Enriched", "protein": 11.50},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic Unbleached Pastry", "protein": 10.00},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic Whole Wheat Hi-Pro Fine", "protein": 14.00},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic Whole Wheat Hi-Pro Medium", "protein": 14.00},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic Whole Wheat Pastry Flour", "protein": 10.00},
  <String, dynamic>{"name": "🇺🇸 Central Milling Organic Whole Wheat Special", "protein": 13.00},
  <String, dynamic>{"name": "🇺🇸 General Mills Washburn's Gold Medal", "protein": 12.60},
  <String, dynamic>{"name": "🇺🇸 GFS Primo Gusto High Gluten", "protein": 13.70},
  <String, dynamic>{"name": "🇺🇸 Gold Medal All Aces Flour", "protein": 12.00},
  <String, dynamic>{"name": "🇺🇸 Gold Medal All Aces Tortilla Flour", "protein": 10.50},
  <String, dynamic>{"name": "🇺🇸 Gold Medal All Trumps High Gluten Flour ", "protein": 14.20},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Big Loaf Flour", "protein": 12.00},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Bread Flour", "protein": 10.00},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Cameo Bakers Flour", "protein": 9.00},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Full Strength", "protein": 12.60},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Full Strength Bakers Flour", "protein": 11.10},
  <String, dynamic>{"name": "🇺🇸 Gold Medal G.M. 44", "protein": 11.00},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Golden Gate Bakers AP Flour", "protein": 8.50},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Golden Shield Bakers Cookie and Pastry", "protein": 12.00},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Harvest King Flour", "protein": 8.30},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Helmet Cake & Pastry Flour", "protein": 13.00},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Hi-Power Flour", "protein": 11.20},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Hotel and Restaurant AP Flour", "protein": 11.20},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Hotel and Restaurant Bakers Flour", "protein": 11.30},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Imperial Bakers Winter Wheat Flour", "protein": 14.20},
  <String, dynamic>{"name": "🇺🇸 Gold Medal King Kaiser Bakers Flour", "protein": 11.10},
  <String, dynamic>{"name": "🇺🇸 Gold Medal King Wheat Bakers Flour", "protein": 11.20},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Medallion AP Flour", "protein": 12.00},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Neapolitan Pizza Flour", "protein": 10.50},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Pollyanna Pie & Cookie Flour", "protein": 8.30},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Purasnow Hi-Ratio Cake Flour", "protein": 13.60},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Remarkable Bakers Flour", "protein": 12.60},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Rex Royal Bakers Flour", "protein": 12.20},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Semolina No. 1", "protein": 11.30},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Sperry Blossoms Bakers Flour", "protein": 9.00},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Sperry Cake & Pastry", "protein": 12.20},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Sperry Extra Fancy Durum Patent Flour", "protein": 13.80},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Stone Ground Wheat-A-Lax", "protein": 12.00},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Stone Ground White Whole Wheat", "protein": 13.80},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Stone Ground Whole Wheat", "protein": 12.60},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Superlative Bakers Flour", "protein": 12.60},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Superlative Hotel & Restaurant AP Flour", "protein": 11.20},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Supreme Flour", "protein": 13.60},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Sureflake Bakers Flour", "protein": 9.50},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Sureloaf Flour", "protein": 12.00},
  <String, dynamic>{"name": "🇺🇸 Gold Medal Wondra Flour", "protein": 10.90},
  <String, dynamic>{"name": "🇺🇸 King Arthur AP Flour ", "protein": 11.70},
  <String, dynamic>{"name": "🇺🇸 King Arthur Bread Flour", "protein": 12.70},
  <String, dynamic>{"name": "🇺🇸 King Arthur Organic Baker's Classic Flour", "protein": 12.70},
  <String, dynamic>{"name": "🇺🇸 King Arthur Organic Baker's Classic with Restored Germ Flour", "protein": 12.70},
  <String, dynamic>{"name": "🇺🇸 King Arthur Organic High Extraction Flour", "protein": 12.90},
  <String, dynamic>{"name": "🇺🇸 King Arthur Organic High Gluten Flour", "protein": 14.10},
  <String, dynamic>{"name": "🇺🇸 King Arthur Organic Pastry Flour", "protein": 9.00},
  <String, dynamic>{"name": "🇺🇸 King Arthur Organic Select Artisan Flour", "protein": 11.70},
  <String, dynamic>{"name": "🇺🇸 King Arthur Organic Type 65 Flour", "protein": 12.70},
  <String, dynamic>{"name": "🇺🇸 King Arthur Organic White Whole Wheat Flour", "protein": 13.20},
  <String, dynamic>{"name": "🇺🇸 King Arthur Organic Whole Wheat Flour", "protein": 14.00},
  <String, dynamic>{"name": "🇺🇸 King Arthur Round Table", "protein": 7.80},
  <String, dynamic>{"name": "🇺🇸 King Arthur Sir Galahad Flour", "protein": 11.70},
  <String, dynamic>{"name": "🇺🇸 King Arthur Sir Lancelot Flour", "protein": 14.00},
  <String, dynamic>{"name": "🇺🇸 King Arthur Special Patent Flour", "protein": 12.70},
  <String, dynamic>{"name": "🇺🇸 King Arthur Type 00 Flour", "protein": 11.00},
  <String, dynamic>{"name": "🇺🇸 King Arthur Unbleached Cake Flour", "protein": 7.00},
  <String, dynamic>{"name": "🇺🇸 King Arthur West Coast Artisan Flour", "protein": 11.70},
  <String, dynamic>{"name": "🇺🇸 King Arthur White Whole Wheat Flour", "protein": 13.00},
  <String, dynamic>{"name": "🇺🇸 King Arthur White Whole Wheat Flour Commercial", "protein": 13.20},
  <String, dynamic>{"name": "🇺🇸 King Arthur Whole Wheat Flour", "protein": 14.00},
  <String, dynamic>{"name": "🇺🇸 Martha White AP Flour", "protein": 9.70},
  <String, dynamic>{"name": "🇺🇸 Pillsbury Bakery A Patent Flour", "protein": 12.60},
  <String, dynamic>{"name": "🇺🇸 Pillsbury Balancer Hi Gluten Flour", "protein": 14.20},
  <String, dynamic>{"name": "🇺🇸 Pillsbury Best Bakers Patent Flour", "protein": 12.90},
  <String, dynamic>{"name": "🇺🇸 Pillsbury Evenloaf High Protein Flour", "protein": 13.60},
  <String, dynamic>{"name": "🇺🇸 Pillsbury Hotel and Restaurant Flour AP", "protein": 11.20},
  <String, dynamic>{"name": "🇺🇸 Pillsbury Potentate High Gluten Flour", "protein": 14.30},
  <String, dynamic>{"name": "🇺🇸 Pillsbury Protector Flour", "protein": 12.00},
  <String, dynamic>{"name": "🇺🇸 Pillsbury So Strong Special Flour High Gluten", "protein": 14.50},
  <String, dynamic>{"name": "🇺🇸 Pillsbury XXXX Patent Flour", "protein": 12.60},
  <String, dynamic>{"name": "🇺🇸 Pillsbury's Best Flour", "protein": 12.90},
  <String, dynamic>{"name": "🇺🇸 Red Rose Artisan", "protein": 11.50},
  <String, dynamic>{"name": "🇺🇸 Red Rose Bleached Bakers Special", "protein": 12.50},
  <String, dynamic>{"name": "🇺🇸 Red Rose Electra Light", "protein": 13.00},
  <String, dynamic>{"name": "🇺🇸 Red Rose Keith’s Best", "protein": 12.50},
  <String, dynamic>{"name": "🇺🇸 Red Rose Type 70 Malted", "protein": 12.50},
  <String, dynamic>{"name": "🇺🇸 Red Rose Type 85 Malted", "protein": 12.50},
  <String, dynamic>{"name": "🇺🇸 Red Rose Whole Wheat Coarse", "protein": 13.50},
  <String, dynamic>{"name": "🇺🇸 Red Rose Whole Wheat Hi-Pro Fine", "protein": 13.50},
  <String, dynamic>{"name": "🇺🇸 Red Rose Whole Wheat Hi-Pro Medium", "protein": 13.50},
  <String, dynamic>{"name": "🇺🇸 White Lily AP Flour", "protein": 6.65},
  <String, dynamic>{"name": "🇺🇸 White Lily Bread Flour", "protein": 13.30},
];

List<Map> getAllFlourNames() {
  return kFlourListGeneric +
      kFlourListItaly +
      kFlourListSpain +
      kFlourListGermany +
      kFlourListAustria +
      kFlourListUS +
      kFlourListJapan;
}

List<Map> flagPositionToList(int position) {
  if (position == 0) {
    if (kDebugMode) print("all flours selected");
    return getAllFlourNames();
  } else if (position == 1) {
    if (kDebugMode) print("it flours selected");
    return kFlourListItaly + kFlourListGeneric;
  } else if (position == 2) {
    if (kDebugMode) print("es flours selected");
    return kFlourListSpain + kFlourListGeneric;
  } else if (position == 3) {
    if (kDebugMode) print("de flours selected");
    return kFlourListGermany + kFlourListGeneric;
  } else if (position == 4) {
    if (kDebugMode) print("at flours selected");
    return kFlourListAustria + kFlourListGeneric;
  } else if (position == 5) {
    if (kDebugMode) print("us flours selected");
    return kFlourListUS + kFlourListGeneric;
  } else if (position == 6) {
    if (kDebugMode) print("jp flours selected");
    return kFlourListJapan + kFlourListGeneric;
  } else {
    return [];
  }
}
